### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by Rachael-Kim** [rachaelkim831/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x]  create blank index.html, styles.css, main.js in vs code. 
- [x]  pick a topdown img of a car from google image.
- [x] insert image on html
