### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by Rachael-Kim** [rachaelkim831/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] create classes for all  4 directions (left, right, down, up) on styles.css
- [x] query the DOM for car's image element.
- [x] add keydown event listener. 
- [x] research keyCode numbers to find out which code belongs to which arrow. 
- [x] write if else chain within event listener function to cover all 4 keyCodes. 
- [x] set class attribute depending on which arrow key user presses.
