### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by Rachael-Kim** [rachaelkim831/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] declare variable x & y on top of the page for coordinates on the page
- [x] use absolute positioning for the car image. 
- [x] research key code # for space bar
- [x] use setInterval method and pass in moveCar function as the first argument and 16 milliseconds as second argument.
