### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by Rachael-Kim** [rachaelkim831/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] declare variable distance within moveCar function  and set to 16 (pixels).
- [x] research about page coordinates.
- [x] write if else chain within moveCar function covering outcomes 4 different directions.
